# Generated by Django 4.0.1 on 2022-02-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='대륙명')),
                ('english_name', models.CharField(max_length=50, unique=True, verbose_name='대륙 영문명')),
            ],
            options={
                'verbose_name': '대륙',
                'verbose_name_plural': '대륙',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='국가명')),
                ('english_name', models.CharField(max_length=50, unique=True, verbose_name='국가 영문명')),
                ('continent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='countries.continent', verbose_name='대륙')),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
            },
        ),
    ]
